### ISSUE TITLE
Facing a Crash. (Log Provided)

### ISSUE THREAD

**Issue by JIREXv1** [DHD2280/BCR-Manager#1]
Opened app
Allowed all permissions
Selected folder where recordings are
Face this error:
[BCRManager_error_report_2024_01_12_14_17_02 .txt](https://github.com/DHD2280/BCR-Manager/files/13924620/BCRManager_error_report_2024_01_12_14_17_02.txt)

**Comment by DHD2280** [comment]
Thank you for log.
Fixed.
Check out [this builld](https://drive.google.com/file/d/1jrVhwKJsi-FVRtvKI0ayR2PjXqVIfvoQ/view?usp=sharing), is pre 1.0.3, I'm implementing a new loging for parsing date and time in filename.
