### ISSUE TITLE
Crash when want play voice

### ISSUE THREAD

**Issue by AlirezaParsi** [DHD2280/BCR-Manager#2]
android 14 
Bcr 1.59
Manager :1.0.4(8)

The second log is more important for me actually 
Log : 
[BCRManager_error_report_2024_01_12_14_17_02.txt](https://github.com/DHD2280/BCR-Manager/files/13943111/BCRManager_error_report_2024_01_12_14_17_02.txt)
[BCRManager_error_report_2024_01_16_00_44_06 .txt](https://github.com/DHD2280/BCR-Manager/files/13943113/BCRManager_error_report_2024_01_16_00_44_06.txt)

**Comment by DHD2280** [comment]
Thank you for logs!

Is the sim number correctly shown in the list?

check this build [v1.1.0 - 13](https://drive.google.com/file/d/16At8k3zghiz4SoHZuLj9RsUVOkSo81fY/view?usp=sharing) and let me know!

Thank you

**Comment by AlirezaParsi** [comment]
https://github.com/DHD2280/BCR-Manager/assets/29276037/0db93a27-0faf-4457-b454-d1bc0bdf16cc
the playing voice was fixed but when i tap to see player its crashing 
log:
[BCRManager_error_report_2024_01_16_09_13_37new .txt](https://github.com/DHD2280/BCR-Manager/files/13945770/BCRManager_error_report_2024_01_16_09_13_37new.txt)



> Thank you for logs!
> 
> Is the sim number correctly shown in the list?
> 
> Do you face this issue on files with JSON or **without** json?
> 
> check this build [v1.1.0 - 13](https://drive.google.com/file/d/16At8k3zghiz4SoHZuLj9RsUVOkSo81fY/view?usp=sharing) and let me know!
> 
> Thank you

**Comment by DHD2280** [comment]
Was the same Issue as Bottom Player Info.
Try [this](https://drive.google.com/file/d/144t0lHPCKxJp97-5wkvxsnMuqspk-lBM/view?usp=sharing).

**Comment by AlirezaParsi** [comment]
Thanks a lot 
Fixed
